FROM node:22-alpine3.21 AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build


FROM node:22-alpine3.21 AS production
WORKDIR /app
COPY --from=base /app/package*.json ./
COPY --from=base /app/dist ./dist
RUN npm ci --omit=dev
ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

CMD ["npm", "start"]
